services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=MyFitness'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'

  rabbitmq:
    image: 'rabbitmq:3-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/'
      - '~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq'
    networks:
      - rabbitmq-network

  fake-email:
    image: 'marcopas/docker-mailslurper:latest'
    ports:
      - '9090:8080'
      - '8585:8585'
      - '25:2500'

networks:
  rabbitmq-network:
    driver: bridge
