services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=MyFitness'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    networks:
      - my-fitness-network

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/'
      - '~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq'
    networks:
      - my-fitness-network

  fake-email:
    image: 'marcopas/docker-mailslurper:latest'
    ports:
      - '9090:8080'
      - '8085:8085'
      - '25:2500'
    networks:
      - my-fitness-network

networks:
  my-fitness-network:
    driver: bridge