spring:
  mail:
    host: 'localhost'
    port: 25

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgres://127.0.0.1:5432/MyFitness"
    username: "admin"
    password: "secret"